INSERT INTO Traits (Name, Type) VALUES ('Melee', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Drive', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Stealth', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Animal Ken', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Etiquette', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Crafts', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Larceny', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Archery', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Riding', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Performance', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Firearms', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Survival', 'skill');
INSERT INTO Traits (Name, Type) VALUES ('Intimidation', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Instruction', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Awareness', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Expression', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Athletics', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Streetwise', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Alertness', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Leadership', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Empathy', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Subterfuge', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Brawl', 'talent');
INSERT INTO Traits (Name, Type) VALUES ('Occult', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Computer', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Seneshal', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Technology', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Law', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Investigation', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Academics', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Medicine', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Politics', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Finance', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Science', 'knowledge');
INSERT INTO Traits (Name, Type) VALUES ('Intelligence', 'mental');
INSERT INTO Traits (Name, Type) VALUES ('Wits', 'mental');
INSERT INTO Traits (Name, Type) VALUES ('Perception', 'mental');
INSERT INTO Traits (Name, Type) VALUES ('Manipulation', 'social');
INSERT INTO Traits (Name, Type) VALUES ('Charisma', 'social');
INSERT INTO Traits (Name, Type) VALUES ('Appearance', 'social');
INSERT INTO Traits (Name, Type) VALUES ('Dexterity', 'physical');
INSERT INTO Traits (Name, Type) VALUES ('Stamina', 'physical');
INSERT INTO Traits (Name, Type) VALUES ('Strength', 'physical');
INSERT INTO Traits (Name, Type) VALUES ('Conviction', 'virtue');
INSERT INTO Traits (Name, Type) VALUES ('Instinct', 'virtue');
INSERT INTO Traits (Name, Type) VALUES ('Willpower', 'virtue');
INSERT INTO Traits (Name, Type) VALUES ('Conscience', 'virtue');
INSERT INTO Traits (Name, Type) VALUES ('Courage', 'virtue');
INSERT INTO Traits (Name, Type) VALUES ('Self-Control', 'virtue');
INSERT INTO Archetypes ('Name') VALUES ('Cavalier');
INSERT INTO Archetypes ('Name') VALUES ('Capitalist');
INSERT INTO Archetypes ('Name') VALUES ('Deviant');
INSERT INTO Archetypes ('Name') VALUES ('Judge');
INSERT INTO Archetypes ('Name') VALUES ('Pedagogue');
INSERT INTO Archetypes ('Name') VALUES ('Curmudgeon');
INSERT INTO Archetypes ('Name') VALUES ('Penitent');
INSERT INTO Archetypes ('Name') VALUES ('Celebrant');
INSERT INTO Archetypes ('Name') VALUES ('Director');
INSERT INTO Archetypes ('Name') VALUES ('Eye of the Storm');
INSERT INTO Archetypes ('Name') VALUES ('Creep Show');
INSERT INTO Archetypes ('Name') VALUES ('Traditionalist');
INSERT INTO Archetypes ('Name') VALUES ('Fanatic');
INSERT INTO Archetypes ('Name') VALUES ('Conniver');
INSERT INTO Archetypes ('Name') VALUES ('Loner');
INSERT INTO Archetypes ('Name') VALUES ('Monster');
INSERT INTO Archetypes ('Name') VALUES ('Rebel');
INSERT INTO Archetypes ('Name') VALUES ('Architect');
INSERT INTO Archetypes ('Name') VALUES ('Sadist');
INSERT INTO Archetypes ('Name') VALUES ('Autocrat');
INSERT INTO Archetypes ('Name') VALUES ('Trickster');
INSERT INTO Archetypes ('Name') VALUES ('Guru');
INSERT INTO Archetypes ('Name') VALUES ('Competitor');
INSERT INTO Archetypes ('Name') VALUES ('Gallant');
INSERT INTO Archetypes ('Name') VALUES ('Child');
INSERT INTO Archetypes ('Name') VALUES ('Caregiver');
INSERT INTO Archetypes ('Name') VALUES ('Masochist');
INSERT INTO Archetypes ('Name') VALUES ('Rogue');
INSERT INTO Archetypes ('Name') VALUES ('Thrill-Seeker');
INSERT INTO Archetypes ('Name') VALUES ('Perfectionist');
INSERT INTO Archetypes ('Name') VALUES ('Idealist');
INSERT INTO Archetypes ('Name') VALUES ('Bravo');
INSERT INTO Archetypes ('Name') VALUES ('Soldier');
INSERT INTO Archetypes ('Name') VALUES ('Chameleon');
INSERT INTO Archetypes ('Name') VALUES ('Conformist');
INSERT INTO Archetypes ('Name') VALUES ('Bon Vivant');
INSERT INTO Archetypes ('Name') VALUES ('Martyr');
INSERT INTO Archetypes ('Name') VALUES ('Sociopath');
INSERT INTO Archetypes ('Name') VALUES ('Survivor');
INSERT INTO Archetypes ('Name') VALUES ('Scientist');
INSERT INTO Archetypes ('Name') VALUES ('Dabbler');
INSERT INTO Archetypes ('Name') VALUES ('Enigma');
INSERT INTO Archetypes ('Name') VALUES ('Visionary');
